/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import core.ChaineProduction;
import core.Entreprise;
import java.util.ArrayList;

/**
 *
 * @author FlorianDELSOL
 */
public class JChercherChaineProduction extends javax.swing.JPanel {
    JFApplication fenetre;
    /**
     * Creates new form JChercherChaineProduction
     */
    public JChercherChaineProduction(JFApplication jframefirst) {
        this.fenetre=jframefirst;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        code = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        Temps = new javax.swing.JLabel();
        correspondance = new javax.swing.JLabel();
        bouton_Chercher = new javax.swing.JButton();
        tempsField = new javax.swing.JSpinner();

        titre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Rechercher une Chaîne de Production");

        code.setText("Code :");

        codeField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });

        nom.setText("Nom :");

        nomField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });

        Temps.setText("Temps :");

        correspondance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correspondance.setText("0 correspondance");

        bouton_Chercher.setText("Chercher");
        bouton_Chercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_ChercherMouseClicked(evt);
            }
        });
        bouton_Chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_ChercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titre)
                            .addComponent(correspondance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Temps, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tempsField))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(bouton_Chercher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temps)
                    .addComponent(tempsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(correspondance)
                .addGap(18, 18, 18)
                .addComponent(bouton_Chercher)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed

    private void bouton_ChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_ChercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_ChercherActionPerformed

    private void bouton_ChercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_ChercherMouseClicked
        ArrayList<ChaineProduction> listechaine = Entreprise.enteprise.chercherChaineDeProduction(this.codeField.getText(), this.nomField.getText(), (int)this.tempsField.getValue());
        if(listechaine.size()!=1){
            this.correspondance.setText(listechaine.size() + " correspondance(s)" );
        }else{
            this.fenetre.changerPanel(new JPDetailChaineProduction(listechaine.get(0)));
        }
    }//GEN-LAST:event_bouton_ChercherMouseClicked
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Temps;
    private javax.swing.JButton bouton_Chercher;
    private javax.swing.JLabel code;
    private javax.swing.JTextField codeField;
    private javax.swing.JLabel correspondance;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nomField;
    private javax.swing.JSpinner tempsField;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
