/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author FlorianDELSOL
 */
public class JMenu extends javax.swing.JPanel {

    private JFApplication fenetre;
    
    /**
     * Creates new form JMenu
     */
    public JMenu(JFApplication fenetre) {
    	this.fenetre=fenetre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        arbre = new javax.swing.JTree();
        prevision = new javax.swing.JButton();

        titre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Menu");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Entreprise");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestion des Stocks");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Etat des stocks");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestion des chaines de production");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Rechercher une chaine de production");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbre.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbreMouseClicked(evt);
            }
        });
        scrollPanel.setViewportView(arbre);

        prevision.setText("Prévision");
        prevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previsionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prevision, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(prevision)
                .addGap(18, 18, 18)
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previsionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previsionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previsionActionPerformed

    private void arbreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbreMouseClicked
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) arbre.getSelectionPath().getLastPathComponent();
        String choix = node.getUserObject().toString();
        javax.swing.JPanel jp;
        switch(choix){
            case "Etat des stocks" :
            	jp = new JStockageGeneral();
                this.fenetre.changerPanel(jp);
            	break;
            case "Rechercher une chaine de production" :
            	jp = new JChercherChaineProduction(this.fenetre);
            	this.fenetre.changerPanel(jp);
                break;
        }
    }//GEN-LAST:event_arbreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbre;
    private javax.swing.JButton prevision;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
