/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import core.ChaineProduction;
import core.Element;
import core.Entreprise;
import core.Production;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FlorianDELSOL
 */
public class JPrevision extends javax.swing.JPanel {
    private DefaultTableModel dcp = new DefaultTableModel();
    private DefaultTableModel dstock = new DefaultTableModel();
    /**
     * Creates new form JChercherChaineProduction
     */
    public JPrevision() {
        Entreprise.enteprise.Prevision();
        initComponents();
        this.dcp = (DefaultTableModel) this.tableau_Chaine_Production.getModel();
        this.dstock = (DefaultTableModel) this.tableau_Stock.getModel();
        this.remplirTable();
    }
    
    private void remplirTable() {
    	ArrayList<Element> stock = Entreprise.enteprise.getListeElement();
        ArrayList<ChaineProduction> listeChaineProduction = Entreprise.enteprise.getListeChaineProduction();
    	for(Element e : stock) {
            Object[] ligne = new Object[]{
               e.getCodeElement(),
               e.getNom(),
               e.getStock().getStock(),
               e.getStock().getUnitee(),
               e.getPrixAchat(),
               e.getPrixVente()
            };
            this.dstock.addRow(ligne);
        }
        for(ChaineProduction cp : listeChaineProduction){
            Object[] ligne = new Object[]{
               cp.getCodeChaineProduction(),
               cp.getNom(),
               cp.getTemps(),
               cp.getNiveauActivitee()
            };
            this.dcp.addRow(ligne);
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        titre = new javax.swing.JLabel();
        titre_Etat_Chaine_Production = new javax.swing.JLabel();
        scroll_Tableau_Stock = new javax.swing.JScrollPane();
        tableau_Stock = new javax.swing.JTable();
        titre_Etat_Stock = new javax.swing.JLabel();
        scroll_Tableau_Chaine_Production = new javax.swing.JScrollPane();
        tableau_Chaine_Production = new javax.swing.JTable();
        exporter = new javax.swing.JButton();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        titre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Prévision");

        titre_Etat_Chaine_Production.setText("Etat de chaque chaine de production ");

        tableau_Stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Nom", "Quantité", "Unité", "Prix à l'achat", "Prix à la vente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scroll_Tableau_Stock.setViewportView(tableau_Stock);

        titre_Etat_Stock.setText("Etat Général des stocks après production");

        tableau_Chaine_Production.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Nom", "Temps de production", "Niveau"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scroll_Tableau_Chaine_Production.setViewportView(tableau_Chaine_Production);

        exporter.setText("Exporter");
        exporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exporterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(exporter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scroll_Tableau_Stock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titre_Etat_Stock)
                            .addComponent(titre_Etat_Chaine_Production))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(scroll_Tableau_Chaine_Production)
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exporter))
                .addGap(18, 18, 18)
                .addComponent(titre_Etat_Chaine_Production)
                .addGap(388, 388, 388)
                .addComponent(titre_Etat_Stock)
                .addGap(18, 18, 18)
                .addComponent(scroll_Tableau_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(scroll_Tableau_Chaine_Production, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exporterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exporterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exporter;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JScrollPane scroll_Tableau_Chaine_Production;
    private javax.swing.JScrollPane scroll_Tableau_Stock;
    private javax.swing.JTable tableau_Chaine_Production;
    private javax.swing.JTable tableau_Stock;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel titre_Etat_Chaine_Production;
    private javax.swing.JLabel titre_Etat_Stock;
    // End of variables declaration//GEN-END:variables
}